### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by matheushdev** [Jeedan/discord-twitch-bot#1]
Hello, good evening, how are you ?
Could you help me for discord?
If yes please pass me?

**Comment by zvshka** [comment]
what's problem?

**Comment by Jeedan** [comment]
> Hello, good evening, how are you ?
> Could you help me for discord?
> If yes please pass me?

what's wrong?

**Comment by matheushdev** [comment]
I wanted help with the twitch API.
Do you disagree?

**Comment by Jeedan** [comment]
What do you need help with? I am very new to using the API so it would be best to read up on it here, this is what i used [twitch api guide](https://dev.twitch.tv/docs/api/guide)

**Comment by matheushdev** [comment]
But could you help me with something you've already done?
Type authentication

**Comment by Jeedan** [comment]
please explain your question in detail? I have no idea what you need help with. Authentication you can find here [Authentication](https://dev.twitch.tv/docs/authentication).

**Comment by matheushdev** [comment]
Okay ;-;

**Comment by matheushdev** [comment]
Did you put in to notify in a chat when a streamer goes online?
Or does it only show the streamer online if it executes the command?

**Comment by Jeedan** [comment]
I display it in the terminal as well as in the discord channel where the command was started. I'm still learning to make it only work in one specific channel

**Comment by matheushdev** [comment]
Do you want help doing this?

**Comment by Jeedan** [comment]
I'm okay for now, thanks though I appreciate the offer!
